#This Vortal Cord v5
#Shizuka Kamishima
title: this vortal cord
url: "http://www.vortalcord.net"
baseurl: ""
markdown: kramdown
timezone: America/Chicago

# blog posts
permalink: /writing/blog/:year-:month-:day-:title.html

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
    
collections:
  writing:
    output: true
    permalink: /writing/:path.html
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "projects"
    values:
      yahPrj: true
  -
    scope:
      path: "resume"
    values:
      yahRes: true
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      yahWrt: true
  -
    scope:
      path: ""
      type: writing
    values:
      library: "misc"
      yahWrt: true
  -
    scope:
      path: "assets"
    values:
      layout: ""
      