#This Vortal Cord v5
#Shizuka Kamishima - 2015-05-09
title: this vortal cord
url: "http://www.vortalcord.net"
baseurl: ""
markdown: kramdown
highlighter: pygments
timezone: America/Chicago

# blog posts
permalink: /writing/blog/:categories/:year-:month-:day-:title.html

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
    
collections:
  writing:
    output: true
    permalink: /writing/:path/:name.html
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      author: "Shizuka Kamishima"
  -
    scope:
      path: ""
      type: writing
    values:
      categories: ['misc']
  - 
    scope:
      path: "about"
    values:
      yahAbt: true
  -
    scope:
      path: "projects"
    values:
      yahPrj: true
  -
    scope:
      path: "resume"
    values:
      yahRes: true
  -
    scope:
      path: "writing"
    values:
      yahLit: true
  -
    scope:
      path: "assets"
    values:
      layout: ""