#This Vortal Cord v5
#Shizuka Kamishima
title: this vortal cord
url: "http://www.vortalcord.net"
baseurl: ""
markdown: kramdown
timezone: America/Chicago

# blog posts
permalink: /writing/blog/:year-:month-:day-:title.html

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
    
collections:
  writing:
    output: true
    permalink: /writing/:path.html
  
defaults:
  -
    scope:
      path: "" # master defaults
    values:
      layout: "page"
      splash: "/assets/img/splash_470x80_blueforest.png"
      
  -
    scope:
      path: "projects"
    values:
      yahPrj: true
      splash: "/assets/img/splash_470x80_code.png"
      
  #== /writing/* ==#
  -
    scope:
      path: ""
      type: posts # from src/_posts/*
    values:
      layout: post
      yahWrt: true
      splash: "/assets/img/splash_470x80_journal.png"
  -
    scope:
      path: ""
      type: writing # from src/_writing/*, collected
    values:
      library: "misc"
      yahWrt: true
      splash: "/assets/img/splash_470x80_journal.png"
  -
    scope:
      path: "writing" # from src/writing/*, non collected
    values:
      yahWrt: true
      splash: "/assets/img/splash_470x80_journal.png"
      
  -
    scope:
      path: "assets"
    values:
      layout: ""
      