#This Vortal Cord v5
#Shizuka Kamishima - 2015-05-09
title: this vortal cord
url: "http://www.vortalcord.net"
baseurl: ""
markdown: kramdown
highlighter: null
timezone: America/Chicago

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      author: "Shizuka Kamishima"
      yahAbt: false
      yahPrj: false
      yahWrk: false
      yahLit: false
  - 
    scope:
      path: "about"
    values:
      yahAbt: true
  -
    scope:
      path: "projects"
    values:
      yahPrj: true
  -
    scope:
      path: "resume"
    values:
      yahRes: true
  -
    scope:
      path: "writing"
    values:
      yahLit: true