#This Vortal Cord v5
#Shizuka Kamishima
title: this vortal cord
url: "http://www.vortalcord.net"
baseurl: ""
markdown: kramdown
timezone: America/Chicago

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
    
collections:
  libraries:
    output: true
    permalink: /writing/:path/
  writing:
    output: true
    permalink: /writing/:path.html
  
defaults:
  -
    scope:
      path: "" # master defaults
    values:
      layout: pg_subpage
      splash: "/assets/img/splash_470x80_blueforest.png"
      
  -
    scope:
      path: "projects"
    values:
      yahPrj: true
      layout: pg_subpage
      root:
        name: projects
        url: /projects
      splash: "/assets/img/splash_470x80_code.png"
      
  -
    scope:
      path: "resume"
      type: pages
    values:
      yahRes: true
      layout: pg_resume
      root:
        name: resumé
        url: /resume
      css:
        - /resume/resume.css
  -
    scope:
      path: ""
      type: writing # from src/_writing/*, collected
    values:
      yahWrt: true
      layout: pg_subpost
      root:
        name: writing
        url: /writing
      splash: "/assets/img/splash_470x80_blueforest.png"
      
  -
    scope:
      path: ""
      type: libraries
    values:
      layout: pg_libindex
      yahWrt: true
      root:
        name: writing
        url: /writing
      splash: "/assets/img/splash_470x80_books.png"
      icon: book
      
  -
    scope:
      path: "assets"
    values:
      layout: ""
  
  # LIBRARIES =======================
  # -
  #   scope:
  #     type: writing
  #     path: "writing/LIBNAME"
  #   values:
  #     library: "LIBNAME"
  #     splash: "/assets/img/splash_470x80_SUBPAGE-DEFAULT-SPLASH.png"
  #
  -
    scope:
      type: writing
      path: "writing/blog"
    values:
      library: "blog"
      splash: "/assets/img/splash_470x80_journal.png"
  -
    scope:
      type: writing
      path: "writing/gamelit"
    values:
      library: "gamelit"
