#This Vortal Cord v5
#Shizuka Kamishima
title: this vortal cord
url: "http://www.vortalcord.net"
baseurl: ""
markdown: kramdown
timezone: America/Chicago

# blog posts
permalink: /writing/blog/:year-:month-:day-:title.html

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
    sass_dir: _sass
    
collections:
  libraries:
    output: true
    permalink: /writing/:path/
  writing:
    output: true
    permalink: /writing/:path.html
  
defaults:
  -
    scope:
      path: "" # master defaults
    values:
      layout: pg_subpage
      splash: "/assets/img/splash_470x80_blueforest.png"
      
  -
    scope:
      path: "projects"
    values:
      yahPrj: true
      layout: pg_subpage
      root:
        name: projects
        url: /projects
      splash: "/assets/img/splash_470x80_code.png"
      
  -
    scope:
      path: "resume"
      type: pages
    values:
      yahRes: true
      layout: pg_resume
      root:
        name: resumé
        url: /resume
      css:
        - /resume/resume.css
  -
    scope:
      path: ""
      type: writing # from src/_writing/*, collected
    values:
      yahWrt: true
      layout: pg_subpost
      root:
        name: writing
        url: /writing
      splash: "/assets/img/splash_470x80_journal.png"
  -
    scope:
      path: "writing" # from src/writing/*, non collected
      type: ""
    values:
      yahWrt: true
      layout: pg_subpost
      root:
        name: writing
        url: /writing
      splash: "/assets/img/splash_470x80_journal.png"
      
  -
    scope:
      path: ""
      type: libraries
    values:
      layout: pg_libindex
      yahWrt: true
      root:
        name: writing
        url: /writing
      splash: "/assets/img/splash_470x80_books.png"
      icon: book
      
  -
    scope:
      path: "assets"
    values:
      layout: ""
      